package weui.icons.filled

import weui.theme.WeUI

/**
 * Filled 风格的图标
 */

private const val Prefix = "icons/filled/"
private const val Suffix = ".svg"

val WeUI.Icons.Filled.AddFriends: String
    get() = "${Prefix}add-friends${Suffix}"
val WeUI.Icons.Filled.Add: String
    get() = "${Prefix}add$Suffix"
val WeUI.Icons.Filled.Add2: String
    get() = "${Prefix}add2$Suffix"
val WeUI.Icons.Filled.Album: String
    get() = "${Prefix}album$Suffix"
val WeUI.Icons.Filled.Arrow: String
    get() = "${Prefix}arrow$Suffix"
val WeUI.Icons.Filled.At: String
    get() = "${Prefix}at$Suffix"
val WeUI.Icons.Filled.Back: String
    get() = "${Prefix}back$Suffix"
val WeUI.Icons.Filled.Back2: String
    get() = "${Prefix}back2$Suffix"
val WeUI.Icons.Filled.BellringOff: String
    get() = "${Prefix}bellring-off$Suffix"
val WeUI.Icons.Filled.BellringOn: String
    get() = "${Prefix}bellring-on$Suffix"
val WeUI.Icons.Filled.Camera: String
    get() = "${Prefix}camera$Suffix"
val WeUI.Icons.Filled.Cellphone: String
    get() = "${Prefix}cellphone$Suffix"
val WeUI.Icons.Filled.Clip: String
    get() = "${Prefix}clip$Suffix"
val WeUI.Icons.Filled.Close: String
    get() = "${Prefix}close$Suffix"
val WeUI.Icons.Filled.Close2: String
    get() = "${Prefix}close2$Suffix"
val WeUI.Icons.Filled.Comment: String
    get() = "${Prefix}comment$Suffix"
val WeUI.Icons.Filled.Contacts: String
    get() = "${Prefix}contacts$Suffix"
val WeUI.Icons.Filled.Copy: String
    get() = "${Prefix}copy$Suffix"
val WeUI.Icons.Filled.DeleteOn: String
    get() = "${Prefix}delete-on$Suffix"
val WeUI.Icons.Filled.Delete: String
    get() = "${Prefix}delete$Suffix"
val WeUI.Icons.Filled.Discover: String
    get() = "${Prefix}discover$Suffix"
val WeUI.Icons.Filled.Display: String
    get() = "${Prefix}display$Suffix"
val WeUI.Icons.Filled.Done: String
    get() = "${Prefix}done$Suffix"
val WeUI.Icons.Filled.Done2: String
    get() = "${Prefix}done2$Suffix"
val WeUI.Icons.Filled.Download: String
    get() = "${Prefix}download$Suffix"
val WeUI.Icons.Filled.Email: String
    get() = "${Prefix}email$Suffix"
val WeUI.Icons.Filled.Error: String
    get() = "${Prefix}error$Suffix"
val WeUI.Icons.Filled.EyesOff: String
    get() = "${Prefix}eyes-off$Suffix"
val WeUI.Icons.Filled.EyesOn: String
    get() = "${Prefix}eyes-on$Suffix"
val WeUI.Icons.Filled.Folder: String
    get() = "${Prefix}folder$Suffix"
val WeUI.Icons.Filled.GroupDetail: String
    get() = "${Prefix}group-detail$Suffix"
val WeUI.Icons.Filled.Help: String
    get() = "${Prefix}help$Suffix"
val WeUI.Icons.Filled.Home: String
    get() = "${Prefix}home$Suffix"
val WeUI.Icons.Filled.Imac: String
    get() = "${Prefix}imac$Suffix"
val WeUI.Icons.Filled.Info: String
    get() = "${Prefix}info$Suffix"
val WeUI.Icons.Filled.Keyboard: String
    get() = "${Prefix}keyboard$Suffix"
val WeUI.Icons.Filled.Like: String
    get() = "${Prefix}like$Suffix"
val WeUI.Icons.Filled.Link: String
    get() = "${Prefix}link$Suffix"
val WeUI.Icons.Filled.Location: String
    get() = "${Prefix}location$Suffix"
val WeUI.Icons.Filled.Lock: String
    get() = "${Prefix}lock$Suffix"
val WeUI.Icons.Filled.MaxWindow: String
    get() = "${Prefix}max-window$Suffix"
val WeUI.Icons.Filled.Me: String
    get() = "${Prefix}me$Suffix"
val WeUI.Icons.Filled.Mike: String
    get() = "${Prefix}mike$Suffix"
val WeUI.Icons.Filled.Mike2: String
    get() = "${Prefix}mike2$Suffix"
val WeUI.Icons.Filled.MobileContacts: String
    get() = "${Prefix}mobile-contacts$Suffix"
val WeUI.Icons.Filled.More: String
    get() = "${Prefix}more$Suffix"
val WeUI.Icons.Filled.More2: String
    get() = "${Prefix}more2$Suffix"
val WeUI.Icons.Filled.Mosaic: String
    get() = "${Prefix}mosaic$Suffix"
val WeUI.Icons.Filled.MusicOff: String
    get() = "${Prefix}music-off$Suffix"
val WeUI.Icons.Filled.Music: String
    get() = "${Prefix}music$Suffix"
val WeUI.Icons.Filled.Note: String
    get() = "${Prefix}note$Suffix"
val WeUI.Icons.Filled.Pad: String
    get() = "${Prefix}pad$Suffix"
val WeUI.Icons.Filled.Pause: String
    get() = "${Prefix}pause$Suffix"
val WeUI.Icons.Filled.Pencil: String
    get() = "${Prefix}pencil$Suffix"
val WeUI.Icons.Filled.PhotoWall: String
    get() = "${Prefix}photo-wall$Suffix"
val WeUI.Icons.Filled.Play: String
    get() = "${Prefix}play$Suffix"
val WeUI.Icons.Filled.Play2: String
    get() = "${Prefix}play2$Suffix"
val WeUI.Icons.Filled.Previous: String
    get() = "${Prefix}previous$Suffix"
val WeUI.Icons.Filled.Previous2: String
    get() = "${Prefix}previous2$Suffix"
val WeUI.Icons.Filled.QrCode: String
    get() = "${Prefix}qr-code$Suffix"
val WeUI.Icons.Filled.Refresh: String
    get() = "${Prefix}refresh$Suffix"
val WeUI.Icons.Filled.ReportProblem: String
    get() = "${Prefix}report-problem$Suffix"
val WeUI.Icons.Filled.Search: String
    get() = "${Prefix}search$Suffix"
val WeUI.Icons.Filled.Sending: String
    get() = "${Prefix}sending$Suffix"
val WeUI.Icons.Filled.Setting: String
    get() = "${Prefix}setting$Suffix"
val WeUI.Icons.Filled.Share: String
    get() = "${Prefix}share$Suffix"
val WeUI.Icons.Filled.Shop: String
    get() = "${Prefix}shop$Suffix"
val WeUI.Icons.Filled.Star: String
    get() = "${Prefix}star$Suffix"
val WeUI.Icons.Filled.Sticker: String
    get() = "${Prefix}sticker$Suffix"
val WeUI.Icons.Filled.Tag: String
    get() = "${Prefix}tag$Suffix"
val WeUI.Icons.Filled.Text: String
    get() = "${Prefix}text$Suffix"
val WeUI.Icons.Filled.Time: String
    get() = "${Prefix}time$Suffix"
val WeUI.Icons.Filled.TransferText: String
    get() = "${Prefix}transfer-text$Suffix"
val WeUI.Icons.Filled.Transfer: String
    get() = "${Prefix}transfer$Suffix"
val WeUI.Icons.Filled.Transfer2: String
    get() = "${Prefix}transfer2$Suffix"
val WeUI.Icons.Filled.Tv: String
    get() = "${Prefix}tv$Suffix"
val WeUI.Icons.Filled.VideoCall: String
    get() = "${Prefix}video-call$Suffix"
val WeUI.Icons.Filled.Voice: String
    get() = "${Prefix}voice$Suffix"
val WeUI.Icons.Filled.VolumeDown: String
    get() = "${Prefix}volume-down$Suffix"
val WeUI.Icons.Filled.VolumeOff: String
    get() = "${Prefix}volume-off$Suffix"
val WeUI.Icons.Filled.VolumeUp: String
    get() = "${Prefix}volume-up$Suffix"