package weui.icons.outlined

import weui.theme.WeUI

/**
 * Outlined 风格的图标
 */

private const val Prefix = "icons/outlined/"
private const val Suffix = ".svg"

val WeUI.Icons.Outlined.AddFriends: String
    get() = "${Prefix}add-friends$Suffix"
val WeUI.Icons.Outlined.Add: String
    get() = "${Prefix}add$Suffix"
val WeUI.Icons.Outlined.Add2: String
    get() = "${Prefix}add2$Suffix"
val WeUI.Icons.Outlined.Album: String
    get() = "${Prefix}album$Suffix"
val WeUI.Icons.Outlined.Arrow: String
    get() = "${Prefix}arrow$Suffix"
val WeUI.Icons.Outlined.At: String
    get() = "${Prefix}at$Suffix"
val WeUI.Icons.Outlined.Back: String
    get() = "${Prefix}back$Suffix"
val WeUI.Icons.Outlined.Back2: String
    get() = "${Prefix}back2$Suffix"
val WeUI.Icons.Outlined.BellringOff: String
    get() = "${Prefix}bellring-off$Suffix"
val WeUI.Icons.Outlined.BellringOn: String
    get() = "${Prefix}bellring-on$Suffix"
val WeUI.Icons.Outlined.Camera: String
    get() = "${Prefix}camera$Suffix"
val WeUI.Icons.Outlined.Cellphone: String
    get() = "${Prefix}cellphone$Suffix"
val WeUI.Icons.Outlined.Clip: String
    get() = "${Prefix}clip$Suffix"
val WeUI.Icons.Outlined.Close: String
    get() = "${Prefix}close$Suffix"
val WeUI.Icons.Outlined.Close2: String
    get() = "${Prefix}close2$Suffix"
val WeUI.Icons.Outlined.Comment: String
    get() = "${Prefix}comment$Suffix"
val WeUI.Icons.Outlined.Contacts: String
    get() = "${Prefix}contacts$Suffix"
val WeUI.Icons.Outlined.Copy: String
    get() = "${Prefix}copy$Suffix"
val WeUI.Icons.Outlined.DeleteOn: String
    get() = "${Prefix}delete-on$Suffix"
val WeUI.Icons.Outlined.Delete: String
    get() = "${Prefix}delete$Suffix"
val WeUI.Icons.Outlined.Discover: String
    get() = "${Prefix}discover$Suffix"
val WeUI.Icons.Outlined.Display: String
    get() = "${Prefix}display$Suffix"
val WeUI.Icons.Outlined.Done: String
    get() = "${Prefix}done$Suffix"
val WeUI.Icons.Outlined.Done2: String
    get() = "${Prefix}done2$Suffix"
val WeUI.Icons.Outlined.Download: String
    get() = "${Prefix}download$Suffix"
val WeUI.Icons.Outlined.Email: String
    get() = "${Prefix}email$Suffix"
val WeUI.Icons.Outlined.Error: String
    get() = "${Prefix}error$Suffix"
val WeUI.Icons.Outlined.EyesOff: String
    get() = "${Prefix}eyes-off$Suffix"
val WeUI.Icons.Outlined.EyesOn: String
    get() = "${Prefix}eyes-on$Suffix"
val WeUI.Icons.Outlined.Folder: String
    get() = "${Prefix}folder$Suffix"
val WeUI.Icons.Outlined.GroupDetail: String
    get() = "${Prefix}group-detail$Suffix"
val WeUI.Icons.Outlined.Help: String
    get() = "${Prefix}help$Suffix"
val WeUI.Icons.Outlined.Home: String
    get() = "${Prefix}home$Suffix"
val WeUI.Icons.Outlined.Imac: String
    get() = "${Prefix}imac$Suffix"
val WeUI.Icons.Outlined.Info: String
    get() = "${Prefix}info$Suffix"
val WeUI.Icons.Outlined.Keyboard: String
    get() = "${Prefix}keyboard$Suffix"
val WeUI.Icons.Outlined.Like: String
    get() = "${Prefix}like$Suffix"
val WeUI.Icons.Outlined.Link: String
    get() = "${Prefix}link$Suffix"
val WeUI.Icons.Outlined.Location: String
    get() = "${Prefix}location$Suffix"
val WeUI.Icons.Outlined.Lock: String
    get() = "${Prefix}lock$Suffix"
val WeUI.Icons.Outlined.MaxWindow: String
    get() = "${Prefix}max-window$Suffix"
val WeUI.Icons.Outlined.Me: String
    get() = "${Prefix}me$Suffix"
val WeUI.Icons.Outlined.Mike: String
    get() = "${Prefix}mike$Suffix"
val WeUI.Icons.Outlined.Mike2: String
    get() = "${Prefix}mike2$Suffix"
val WeUI.Icons.Outlined.MobileContacts: String
    get() = "${Prefix}mobile-contacts$Suffix"
val WeUI.Icons.Outlined.More: String
    get() = "${Prefix}more$Suffix"
val WeUI.Icons.Outlined.More2: String
    get() = "${Prefix}more2$Suffix"
val WeUI.Icons.Outlined.Mosaic: String
    get() = "${Prefix}mosaic$Suffix"
val WeUI.Icons.Outlined.MusicOff: String
    get() = "${Prefix}music-off$Suffix"
val WeUI.Icons.Outlined.Music: String
    get() = "${Prefix}music$Suffix"
val WeUI.Icons.Outlined.Note: String
    get() = "${Prefix}note$Suffix"
val WeUI.Icons.Outlined.Pad: String
    get() = "${Prefix}pad$Suffix"
val WeUI.Icons.Outlined.Pause: String
    get() = "${Prefix}pause$Suffix"
val WeUI.Icons.Outlined.Pencil: String
    get() = "${Prefix}pencil$Suffix"
val WeUI.Icons.Outlined.PhotoWall: String
    get() = "${Prefix}photo-wall$Suffix"
val WeUI.Icons.Outlined.Play: String
    get() = "${Prefix}play$Suffix"
val WeUI.Icons.Outlined.Play2: String
    get() = "${Prefix}play2$Suffix"
val WeUI.Icons.Outlined.Previous: String
    get() = "${Prefix}previous$Suffix"
val WeUI.Icons.Outlined.Previous2: String
    get() = "${Prefix}previous2$Suffix"
val WeUI.Icons.Outlined.QrCode: String
    get() = "${Prefix}qr-code$Suffix"
val WeUI.Icons.Outlined.Refresh: String
    get() = "${Prefix}refresh$Suffix"
val WeUI.Icons.Outlined.ReportProblem: String
    get() = "${Prefix}report-problem$Suffix"
val WeUI.Icons.Outlined.Search: String
    get() = "${Prefix}search$Suffix"
val WeUI.Icons.Outlined.Sending: String
    get() = "${Prefix}sending$Suffix"
val WeUI.Icons.Outlined.Setting: String
    get() = "${Prefix}setting$Suffix"
val WeUI.Icons.Outlined.Share: String
    get() = "${Prefix}share$Suffix"
val WeUI.Icons.Outlined.Shop: String
    get() = "${Prefix}shop$Suffix"
val WeUI.Icons.Outlined.Star: String
    get() = "${Prefix}star$Suffix"
val WeUI.Icons.Outlined.Sticker: String
    get() = "${Prefix}sticker$Suffix"
val WeUI.Icons.Outlined.Tag: String
    get() = "${Prefix}tag$Suffix"
val WeUI.Icons.Outlined.Text: String
    get() = "${Prefix}text$Suffix"
val WeUI.Icons.Outlined.Time: String
    get() = "${Prefix}time$Suffix"
val WeUI.Icons.Outlined.TransferText: String
    get() = "${Prefix}transfer-text$Suffix"
val WeUI.Icons.Outlined.Transfer: String
    get() = "${Prefix}transfer$Suffix"
val WeUI.Icons.Outlined.Transfer2: String
    get() = "${Prefix}transfer2$Suffix"
val WeUI.Icons.Outlined.Tv: String
    get() = "${Prefix}tv$Suffix"
val WeUI.Icons.Outlined.VideoCall: String
    get() = "${Prefix}video-call$Suffix"
val WeUI.Icons.Outlined.Voice: String
    get() = "${Prefix}voice$Suffix"
val WeUI.Icons.Outlined.VolumeDown: String
    get() = "${Prefix}volume-down$Suffix"
val WeUI.Icons.Outlined.VolumeOff: String
    get() = "${Prefix}volume-off$Suffix"
val WeUI.Icons.Outlined.VolumeUp: String
    get() = "${Prefix}volume-up$Suffix"